version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: ./amp-api
    command: bash -c "./wait-for-it.sh db:5432 -- rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./amp-api:/rails
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/app_development"
      RAILS_ENV: development

  client:
    build: ./amp-client
    command: /bin/sh -c "npm install && npm run dev -- --host 0.0.0.0"
    volumes:
      - ./amp-client:/usr/src/app
    ports:
      - "5173:5173"

volumes:
  db-data:
